Repository matthewl121/CustomRegistry, pull requests merged in 2024-10, with the labels that each got.

#44 #43 Reconfigured successful GHA CI/CD Build
  .github/workflows/eslint.yml
  .gitignore
  api/download.ts
  package-lock.json
  package.json
  results/eslint-results.sarif
  src/api/apiUtils.js
  src/api/githubApi.js
  src/api/graphqlQueries.js
  src/api/npmApi.js
  src/index.js
  src/index.ts
  src/metricCalcs.js
  src/types.js
  src/utils/log.js
  src/utils/urlHandler.js
  src/utils/utils.js
  test/test_output.js
Labels: bug, enhancement, help wanted

#45 Refactor Phase 1 Metrics
  src/index.js
  src/index.ts
  src/metricCalcs.ts
  src/metrics/busFactor.ts
  src/metrics/correctness.ts
  src/metrics/dependencyPinning.ts
  src/metrics/license.ts
  src/metrics/metric.js
  src/metrics/metric.ts
  src/metrics/netScore.js
  src/metrics/netScore.ts
  src/metrics/rampUp.ts
  src/metrics/responsiveMaintainer.ts
  src/types.ts
  src/utils/log.js
  src/utils/worker.ts
Labels: enhancement, good first issue

#50 Matt branch
  .github/workflows/lambda.yml
  deploy.zip
  package-lock.json
  package.json
Labels: documentation, urgent

#54 #20 Fix timeout error for tests
  test/index.test.ts
Labels: bug, enhancement
